const keyNames = {
  // Level start string keys
  kA1: 'AudioTrack',
  kA2: 'Gamemode',
  kA3: 'Mini Mode',
  kA4: 'Speed',
  kA5: 'Obj-2 Blending',
  kA6: 'Background Texture ID',
  kA7: 'Ground Texture ID',
  kA8: 'Dual Mode',
  kA9: 'Level/Start Pos Object',
  kA10: '2-Player Mode',
  kA11: 'Flip Gravity',
  kA12: 'Color3 Blending (UNUSED)',
  kA13: 'Song Offset',
  kA14: 'Guidelines',
  kA15: 'Fade In',
  kA16: 'Fade Out',
  kA17: 'Ground Line',
  kA18: 'Font',
  kA20: 'Reverse Gameplay',
  kA22: 'Platformer Mode',
  kA25: 'Middleground Texture ID',
  kA27: 'Allow Multi-Rotation',
  kA28: 'Mirror Mode',
  kA29: 'Rotate Gameplay',
  kA31: 'Enable Player Squeeze',
  kA32: 'Fix Gravity Bug',
  kA33: 'Fix Negative Scale',
  kA34: 'Fix Robot Jump',
  kA36: 'Spawn Group',
  kA37: 'Dynamic Level Height',
  kA38: 'Sort Groups',
  kA39: 'Fix Radius Collision',
  kA40: 'Enable 2.2 Changes',
  kA41: 'Allow Static-Rotate',
  kA42: 'Reverse Sync',
  kA43: 'No Time Penalty',
  kA45: 'Decrease Boost Slide',
  kS38: 'Colors',
  kS39: 'Color Page',
  // Object string keys
  '1': 'Object ID',
  '2': 'X Position',
  '3': 'Y Position',
  '4': 'Flipped Horizontally',
  '5': 'Flipped Vertically',
  '6': 'Rotation',
  '7': 'Red',
  '8': 'Green',
  '9': 'Blue',
  '10': 'Duration',
  '11': 'Touch Triggered',
  '12': 'Secret Coin ID',
  '13': 'Special Object Checked',
  '14': 'Tint Ground',
  '15': 'Player Color 1',
  '16': 'Player Color 2',
  '17': 'Blending',
  '19': '1.9 Color Channel ID',
  '20': 'Editor Layer 1',
  '21': 'Main Color Channel ID',
  '22': 'Secondary Color Channel ID',
  '23': 'Target Color ID',
  '24': 'Z Layer',
  '25': 'Z Order',
  '28': 'Offset X',
  '29': 'Offset Y',
  '30': 'Easing',
  '31': 'Text',
  '32': 'Scaling',
  '33': 'Single Group ID',
  '34': 'Group Parent',
  '35': 'Opacity',
  '41': 'Main Color HSV Enabled',
  '42': 'Secondary Color HSV Enabled',
  '43': 'Main Color HSV',
  '44': 'Secondary Color HSV',
  '45': 'Fade In',
  '46': 'Hold',
  '47': 'Fade Out',
  '48': 'Pulse Mode',
  '49': 'Copied Color HSV',
  '50': 'Copied Color ID',
  '51': 'Target Group ID',
  '52': 'Pulse Target Type',
  '54': 'Yellow Teleportation Portal Y Offset',
  '55': 'Teleport Portal Ease',
  '56': 'Activate Group',
  '57': 'Group IDs',
  '58': 'Lock To Player X',
  '59': 'Lock To Player Y',
  '60': 'Copy Opacity',
  '61': 'Editor Layer 2',
  '62': 'Spawn Triggered',
  '63': 'Spawn Delay',
  '64': "Don't Fade",
  '65': 'Main Only',
  '66': 'Detail Only',
  '67': "Don't Enter",
  '68': 'Degrees',
  '69': 'Times 360',
  '70': 'Lock Object Rotation',
  '71': 'Secondary Group ID',
  '72': 'X Mod',
  '73': 'Y Mod',
  '75': 'Strength',
  '76': 'Animation ID',
  '77': 'Count',
  '78': 'Subtract Count',
  '79': 'Pickup Mode',
  '80': 'Item/Block ID',
  '81': 'Hold Mode',
  '82': 'Toggle Mode',
  '84': 'Interval',
  '85': 'Easing Rate',
  '86': 'Exclusive',
  '87': 'Multi-Trigger',
  '88': 'Comparison',
  '89': 'Dual Mode',
  '90': 'Speed',
  '91': 'Follow Delay',
  '92': 'Y Offset',
  '93': 'Trigger On Exit',
  '94': 'Dynamic Block',
  '95': 'Block B ID',
  '96': 'Disable Glow',
  '97': 'Custom Rotation Speed',
  '98': 'Disable Rotation',
  '99': 'Multi Activate (Orbs)',
  '100': 'Enable Use Target',
  '101': 'Target Pos Coordinates',
  '102': 'Editor Disable',
  '103': 'High Detail',
  '104': 'Multi Activate (Triggers)',
  '105': 'Max Speed',
  '106': 'Randomize Start',
  '107': 'Animation Speed',
  '108': 'Linked Group ID',
  '110': 'Exit Static',
  '111': 'Free Mode',
  '112': 'Edit Camera Settings',
  '113': 'Easing (Free Mode)',
  '114': 'Padding',
  '115': 'ord',
  '116': 'No Effects',
  '117': 'Reverse',
  '120': 'Time Mod',
  '121': 'No Touch',
  '128': 'Scale X',
  '131': 'Warp Y angle',
  '132': 'Warp X angle'
};

module.exports = { keyNames };
