export type KeyInfo = { name: string; type: string };

export const keyMapping: Record<string, KeyInfo> = {
  // Level start keys
  kA1: { name: 'AudioTrack', type: 'integer' },
  kA2: { name: 'Gamemode', type: 'Gamemode (enum)' },
  kA3: { name: 'Mini Mode', type: 'bool' },
  kA4: { name: 'Speed', type: 'Speed (enum)' },
  kA5: { name: 'Obj-2 Blending', type: 'bool' },
  kA6: { name: 'Background Texture ID', type: 'integer' },
  kA7: { name: 'Ground Texture ID', type: 'integer' },
  kA8: { name: 'Dual Mode', type: 'bool' },
  kA9: { name: 'Level/Start Pos Object', type: 'bool' },
  kA10: { name: '2-Player Mode', type: 'bool' },
  kA11: { name: 'Flip Gravity', type: 'bool' },
  kA12: { name: 'Color3 Blending (UNUSED)', type: 'bool' },
  kA13: { name: 'Song Offset', type: 'float' },
  kA14: { name: 'Guidelines', type: 'Guideline String' },
  kA15: { name: 'Fade In', type: 'bool' },
  kA16: { name: 'Fade Out', type: 'bool' },
  kA17: { name: 'Ground Line', type: 'integer' },
  kA18: { name: 'Font', type: 'integer' },
  kA20: { name: 'Reverse Gameplay', type: 'bool' },
  kA22: { name: 'Platformer Mode', type: 'bool' },
  kA25: { name: 'Middleground Texture ID', type: 'integer' },
  kA27: { name: 'Allow Multi-Rotation', type: 'bool' },
  kA28: { name: 'Mirror Mode', type: 'bool' },
  kA29: { name: 'Rotate Gameplay', type: 'bool' },
  kA31: { name: 'Enable Player Squeeze', type: 'bool' },
  kA32: { name: 'Fix Gravity Bug', type: 'bool' },
  kA33: { name: 'Fix Negative Scale', type: 'bool' },
  kA34: { name: 'Fix Robot Jump', type: 'bool' },
  kA36: { name: 'Spawn Group', type: 'integer' },
  kA37: { name: 'Dynamic Level Height', type: 'bool' },
  kA38: { name: 'Sort Groups', type: 'bool' },
  kA39: { name: 'Fix Radius Collision', type: 'bool' },
  kA40: { name: 'Enable 2.2 Changes', type: 'bool' },
  kA41: { name: 'Allow Static-Rotate', type: 'bool' },
  kA42: { name: 'Reverse Sync', type: 'bool' },
  kA43: { name: 'No Time Penalty', type: 'bool' },
  kA45: { name: 'Decrease Boost Slide', type: 'bool' },
  kS38: { name: 'Colors', type: 'Color String' },
  kS39: { name: 'Color Page', type: 'integer' },

  // Object keys
  '1': { name: 'Object ID', type: 'integer' },
  '2': { name: 'X Position', type: 'float' },
  '3': { name: 'Y Position', type: 'float' },
  '4': { name: 'Flipped Horizontally', type: 'bool' },
  '5': { name: 'Flipped Vertically', type: 'bool' },
  '6': { name: 'Rotation', type: 'float' },
  '7': { name: 'Red', type: 'integer' },
  '8': { name: 'Green', type: 'integer' },
  '9': { name: 'Blue', type: 'integer' },
  '10': { name: 'Duration', type: 'float' },
  '11': { name: 'Touch Triggered', type: 'bool' },
  '12': { name: 'Secret Coin ID', type: 'integer' },
  '13': { name: 'Special Object Checked', type: 'bool' },
  '14': { name: 'Tint Ground', type: 'bool' },
  '15': { name: 'Player Color 1', type: 'bool' },
  '16': { name: 'Player Color 2', type: 'bool' },
  '17': { name: 'Blending', type: 'bool' },
  '19': { name: '1.9 Color Channel ID', type: 'integer' },
  '20': { name: 'Editor Layer 1', type: 'integer' },
  '21': { name: 'Main Color Channel ID', type: 'integer' },
  '22': { name: 'Secondary Color Channel ID', type: 'integer' },
  '23': { name: 'Target Color ID', type: 'integer' },
  '24': { name: 'Z Layer', type: 'integer' },
  '25': { name: 'Z Order', type: 'integer' },
  '28': { name: 'Offset X', type: 'integer' },
  '29': { name: 'Offset Y', type: 'integer' },
  '30': { name: 'Easing', type: 'Easing (enum)' },
  '31': { name: 'Text', type: 'string (base64)' },
  '32': { name: 'Scaling', type: 'float' },
  '33': { name: 'Single Group ID', type: 'integer' },
  '34': { name: 'Group Parent', type: 'bool' },
  '35': { name: 'Opacity', type: 'float' },
  '41': { name: 'Main Color HSV Enabled', type: 'bool' },
  '42': { name: 'Secondary Color HSV Enabled', type: 'bool' },
  '43': { name: 'Main Color HSV', type: 'HSV' },
  '44': { name: 'Secondary Color HSV', type: 'HSV' },
  '45': { name: 'Fade In', type: 'float' },
  '46': { name: 'Hold', type: 'float' },
  '47': { name: 'Fade Out', type: 'float' },
  '48': { name: 'Pulse Mode', type: 'Pulse Mode (enum)' },
  '49': { name: 'Copied Color HSV', type: 'HSV' },
  '50': { name: 'Copied Color ID', type: 'integer' },
  '51': { name: 'Target Group ID', type: 'integer' },
  '52': { name: 'Pulse Target Type', type: 'Pulse Target Type (enum)' },
  '54': { name: 'Yellow Teleportation Portal Y Offset', type: 'float' },
  '55': { name: 'Teleport Portal Ease', type: 'bool' },
  '56': { name: 'Activate Group', type: 'bool' },
  '57': { name: 'Group IDs', type: 'integer array' },
  '58': { name: 'Lock To Player X', type: 'bool' },
  '59': { name: 'Lock To Player Y', type: 'bool' },
  '60': { name: 'Copy Opacity', type: 'bool' },
  '61': { name: 'Editor Layer 2', type: 'integer' },
  '62': { name: 'Spawn Triggered', type: 'bool' },
  '63': { name: 'Spawn Delay', type: 'float' },
  '64': { name: "Don't Fade", type: 'bool' },
  '65': { name: 'Main Only', type: 'bool' },
  '66': { name: 'Detail Only', type: 'bool' },
  '67': { name: "Don't Enter", type: 'bool' },
  '68': { name: 'Degrees', type: 'integer' },
  '69': { name: 'Times 360', type: 'integer' },
  '70': { name: 'Lock Object Rotation', type: 'bool' },
  '71': { name: 'Secondary Group ID', type: 'integer' },
  '72': { name: 'X Mod', type: 'float' },
  '73': { name: 'Y Mod', type: 'float' },
  '75': { name: 'Strength', type: 'float' },
  '76': { name: 'Animation ID', type: 'integer' },
  '77': { name: 'Count', type: 'integer' },
  '78': { name: 'Subtract Count', type: 'bool' },
  '79': { name: 'Pickup Mode', type: 'Pickup Item Mode (enum)' },
  '80': { name: 'Item/Block ID', type: 'integer' },
  '81': { name: 'Hold Mode', type: 'bool' },
  '82': { name: 'Toggle Mode', type: 'Touch Toggle Mode (enum)' },
  '84': { name: 'Interval', type: 'float' },
  '85': { name: 'Easing Rate', type: 'float' },
  '86': { name: 'Exclusive', type: 'bool' },
  '87': { name: 'Multi-Trigger', type: 'bool' },
  '88': { name: 'Comparison', type: 'Instant Count Comparison (enum)' },
  '89': { name: 'Dual Mode', type: 'bool' },
  '90': { name: 'Speed', type: 'float' },
  '91': { name: 'Follow Delay', type: 'float' },
  '92': { name: 'Y Offset', type: 'float' },
  '93': { name: 'Trigger On Exit', type: 'bool' },
  '94': { name: 'Dynamic Block', type: 'bool' },
  '95': { name: 'Block B ID', type: 'integer' },
  '96': { name: 'Disable Glow', type: 'bool' },
  '97': { name: 'Custom Rotation Speed', type: 'float' },
  '98': { name: 'Disable Rotation', type: 'bool' },
  '99': { name: 'Multi Activate (Orbs)', type: 'bool' },
  '100': { name: 'Enable Use Target', type: 'bool' },
  '101': { name: 'Target Pos Coordinates', type: 'Target Pos Coordinates (enum)' },
  '102': { name: 'Editor Disable', type: 'bool' },
  '103': { name: 'High Detail', type: 'bool' },
  '104': { name: 'Multi Activate (Triggers)', type: 'bool' },
  '105': { name: 'Max Speed', type: 'float' },
  '106': { name: 'Randomize Start', type: 'bool' },
  '107': { name: 'Animation Speed', type: 'float' },
  '108': { name: 'Linked Group ID', type: 'integer' },
  '110': { name: 'Exit Static', type: 'bool' },
  '111': { name: 'Free Mode', type: 'bool' },
  '112': { name: 'Edit Camera Settings', type: 'bool' },
  '113': { name: 'Easing (Free Mode)', type: 'integer' },
  '114': { name: 'Padding', type: 'float' },
  '115': { name: 'ord', type: 'integer' },
  '116': { name: 'No Effects', type: 'bool' },
  '117': { name: 'Reverse', type: 'bool' },
  '120': { name: 'Time Mod', type: 'float' },
  '121': { name: 'No Touch', type: 'bool' },
  '128': { name: 'Scale X', type: 'float' },
  '131': { name: 'Warp Y angle', type: 'float' },
  '132': { name: 'Warp X angle', type: 'float' }
};

export default { keyMapping };
